[SONIC-1384] Build BpkFlightLeg in Backpack
Skyscanner/backpack-ios pull request #1620
Opened 2023-03-27 15:29 UTC by michmaml

# JIRA
https://skyscanner.atlassian.net/browse/SONIC-1384

# Why these changes
Flight Leg was the last unbuilt component in Backpack. This PR only contains its implementation in UIKit and SwiftUI's version will be built in the future. This pull request introduces the actual BPK component, a controller which generates four examples in _Example/_ folder and a test file to tests the snapshots.

## Screenshots
**Light Mode** | **Dark Mode** 
---|---
![light mode](https://user-images.githubusercontent.com/55076036/227986310-21f4046f-d3dc-4f0a-b34a-2867f9dc0fb3.jpg) | ![dark mode](https://user-images.githubusercontent.com/55076036/227987056-4a7809cd-d9e2-46c1-842b-7ef55dc877a3.jpg)

_<sub><sup>This is my first iOS PR so any feedback, comments and corrections are welcome</sup></sub>_
---
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/main/CONTRIBUTING.md)

Remember to include the following changes:
+ [x] `README.md`
+ [x] Tests
+ [x] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Screenshots.swift)
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/main/Backpack/Backpack.h)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GUIDELINES.md)_

2023-03-28 15:28 UTC, gert-janvercauteren reviewed
Could you please add a README.md for this new component?

2023-03-28 16:40 UTC, michmaml commented
^ Just added the [README](https://github.com/Skyscanner/backpack-ios/blob/sonic/SONIC-1384-bpk-flightleg-uikit/Backpack/FlightLeg/README.md). 😄

2023-03-29 10:42 UTC, frugoman requested changes
BPKFlightLegSnapshotTest.swift is in the wrong folder and this made the snapshots be generated in the wrong place. Please relocate the files!

2023-03-29 10:42 UTC, frugoman commented on Backpack/FlightLeg/Classes/BPKFlightLeg.swift
> +    private func setupFlightStackView() -> UIView {
can you rename this function to reflect that's actually creating flight stack? something like `createFlightStackView` or `makeFlig...`

2023-03-29 10:42 UTC, frugoman commented on Backpack/FlightLeg/Classes/BPKFlightLeg.swift
> +    private func setupDurationStackView() -> UIView {
same as above, if it's setting up, there's no need to return it.

I would keep the setup as is maybe and just have it not return anything.

2023-03-29 12:50 UTC, michmaml commented on Backpack/FlightLeg/Classes/BPKFlightLeg.swift
> +    private var carrierLogo: BPKIconName
Thank you for pointing it out! I am not sure if `highlightStopsInfo` can be set to a constant, as the line 140 shows an error _Immutable value 'self.highlightStopsInfo' may only be initialized once_.

2023-03-30 12:27 UTC, frugoman approved these changes

2023-03-30 12:41 UTC, merged