KOA-6250 SwiftUI BPKNudger, add optional icon
Skyscanner/backpack-ios pull request #1757
Opened 2023-09-05 03:10 UTC by gert-janvercauteren

# SwiftUI BPKNudger

Add optional icon to BPKNudger

| Day | Night |
| --- | --- | 
| <img width="375" alt="iPhone-swiftui_nudger___default_lm" src="https://github.com/Skyscanner/backpack-ios/assets/728889/7d4a2aa1-d42f-4605-b903-d161e4122525"> | <img width="375" alt="iPhone-swiftui_nudger___default_dm" src="https://github.com/Skyscanner/backpack-ios/assets/728889/d0679234-2287-43e6-b14d-f54e4d14313d"> |

+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/main/CONTRIBUTING.md)

Remember to include the following changes:
+ [ ] `README.md`
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Screenshots.swift)
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/main/Backpack/Backpack.h)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GUIDELINES.md)_

2023-09-05 08:05 UTC, olliecurtis approved these changes

2023-09-05 11:15 UTC, frugoman commented on Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
> +                HStack(alignment: subtitle == nil ? .center : .top, spacing: .md) {
The icon needs to be centred in the row, not with the title alone. I think this condition should be inverted?

![image](https://github.com/Skyscanner/backpack-ios/assets/13455159/975e5063-c1ca-4c3c-af0a-c621b1f4307e)

2023-09-05 11:16 UTC, frugoman requested changes

2023-09-05 11:16 UTC, frugoman commented on Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
> +                HStack(alignment: subtitle == nil ? .center : .top, spacing: .md) {
The icon needs to be centred in the row, not with the title alone. I think this condition should be inverted?
from figma:  ![image](https://github.com/Skyscanner/backpack-ios/assets/13455159/975e5063-c1ca-4c3c-af0a-c621b1f4307e)

2023-09-06 10:01 UTC, frugoman approved these changes

2023-09-06 11:46 UTC, merged