[NO-JIRA] Add option to customize bottom sheet insets
Skyscanner/backpack-ios pull request #873
Opened 2021-01-28 03:47 UTC by jookes

This PR introduces an extra `insets` parameter to the BottomSheet initialization call. This allows for greater customization. 

The defaults that were used in ModalBottomSheetLayout and PersistentBottomSheetLayout have been copied over to a new BottomSheetInset struct. 

+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/master/CONTRIBUTING.md)

Remember to include the following changes:
+ [ ] `UNRELEASED.md`
+ [ ] `README.md`
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/master/Example/Backpack%20Screenshot/Screenshots.swift)
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Backpack.h)
+ [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

2021-02-02 14:16 UTC, georgegillams commented on Example/Backpack.xcodeproj/project.pbxproj
> +D28F6B8923A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf in Resources */ = {isa = PBXBuildFile; fileRef = D28F6B8123A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf */; };
Could this be reverted plz?

2021-02-02 14:16 UTC, georgegillams commented on Example/Backpack.xcodeproj/project.pbxproj
> +D28F6B8123A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "SkyscannerRelativeiOS-Black.ttf"; sourceTree = "<group>"; };
Same as above

2021-02-02 14:16 UTC, georgegillams requested changes
Sorry for the delay. Looks good to me except a couple of files that need reverting 👍

2021-02-03 01:46 UTC, jookes commented on Example/Backpack.xcodeproj/project.pbxproj
> +D28F6B8923A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf in Resources */ = {isa = PBXBuildFile; fileRef = D28F6B8123A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf */; };
Reverted!

2021-02-03 01:46 UTC, jookes commented on Example/Backpack.xcodeproj/project.pbxproj
> +D28F6B8123A1091D001A188F /* SkyscannerRelativeiOS-Black.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "SkyscannerRelativeiOS-Black.ttf"; sourceTree = "<group>"; };
Reverted!

2021-02-04 11:50 UTC, georgegillams approved these changes

2021-02-04 12:22 UTC, merged